version: "2"

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
      - rabbitmq
    command: rabbitmq:5672

  api:
    build: ./Collectively.Api/src/Collectively.Api
    links:
      - rabbitmq
      - redis
      - storage-service
    ports:
      - '5000:5000'

  storage-service:
    build: ./Collectively.Services.Storage/src/Collectively.Services.Storage
    links:
      - mongo
      - rabbitmq
      - redis
      - users-service
      - remarks-service
      - operations-service
      - statistics-service
      - notifications-service
    ports:
      - '10000:10000'  

  users-service:
    build: ./Collectively.Services.Users/src/Collectively.Services.Users
    links:
      - mongo
      - rabbitmq
    ports:
      - '10002:10002'

  remarks-service:
    build: ./Collectively.Services.Remarks/src/Collectively.Services.Remarks
    links:
      - mongo
      - rabbitmq
    ports:
      - '10003:10003'    

  operations-service:
    build: ./Collectively.Services.Operations/src/Collectively.Services.Operations
    links:
      - mongo
      - rabbitmq
    ports:
      - '10001:10001'

  medium-service:
    build: ./Collectively.Services.Medium/src/Collectively.Services.Medium
    links:
      - mongo
      - rabbitmq
    ports:
      - '11000:11000'

  mailing-service:
    build: ./Collectively.Services.Mailing/src/Collectively.Services.Mailing
    links:
      - mongo
      - rabbitmq
    ports:
      - '10006:10006'

  notifications-service:
    build: ./Collectively.Services.Notifications/src/Collectively.Services.Notifications
    links:
      - mongo
      - rabbitmq
    ports:
      - '10005:10005'      

  statistics-service:
    build: ./Collectively.Services.Statistics/src/Collectively.Services.Statistics
    links:
      - mongo
      - rabbitmq
    ports:
      - '10004:10004'  

  supervisor-service:
    build: ./Collectively.Services.Supervisor/src/Collectively.Services.Supervisor
    links:
      - mongo
      - rabbitmq
      - api
      - mailing-service
      - medium-service
      - operations-service
      - remarks-service
      - statistics-service
      - storage-service
      - users-service
    ports:
      - '11001:11001'

  websockets-service:
    build: ./Collectively.Services.Websockets/src
    links:
      - rabbitmq
    ports:
      - '9050:9050'

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis
    ports:
      - '6379:6379'