version: "2"

services:
  api:
    image: noordwind/collectively.api
    links:
      - lockbox
      - storage-service
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=api'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  signalr-service:
    image: noordwind/collectively.services.signalr
    links:
      - rabbitmq
      - lockbox
      - remarks-service
    ports:
      - '10010:10010'  
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=signalr-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  storage-service:
    image: noordwind/collectively.services.storage
    links:
      - lockbox
      - users-service
      - remarks-service
      - operations-service
      - statistics-service
      - notifications-service
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=storage-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  users-service:
    image: noordwind/collectively.services.users
    links:
      - lockbox
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=users-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  remarks-service:
    image: noordwind/collectively.services.remarks
    links:
      - lockbox
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=remarks-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  operations-service:
    image: noordwind/collectively.services.operations
    links:
      - lockbox
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=operations-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  medium-service:
    image: noordwind/collectively.services.medium
    links:
      - lockbox
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=medium-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  mailing-service:
    image: noordwind/collectively.services.mailing
    links:
      - lockbox
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=mailing-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  notifications-service:
    image: noordwind/collectively.services.notifications
    links:
      - lockbox
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=notifications-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  statistics-service:
    image: noordwind/collectively.services.statistics
    links:
      - lockbox
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=statistics-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  supervisor-service:
    image: noordwind/collectively.services.supervisor
    links:
      - lockbox
      - api
      - mailing-service
      - medium-service
      - notifications-service
      - operations-service
      - remarks-service
      - statistics-service
      - storage-service
      - signalr-service
      - users-service
    environment:
    - 'LOCKBOX_API_KEY=YOUR_LOCKBOX_API_KEY'
    - 'LOCKBOX_API_URL=http://lockbox:12000'
    - 'LOCKBOX_BOX_NAME=supervisor-service'
    - 'LOCKBOX_ENCRYPTION_KEY=YOUR_LOCKBOX_ENCRYPTION_KEY'
    - 'LOCKBOX_ENTRY_KEY=appsettings'

  web:
    image: noordwind/collectively.web

  lockbox:
    image: lockbox/lockbox.server
    environment:
      - 'ASPNETCORE_URLS=http://*:12000'
      - 'LOCKBOX_MONGO_CONNECTION_STRING=mongodb://MONGO_HOST:27017/Lockbox'
      - 'LOCKBOX_MONGO_DATABASE=Lockbox'
      - 'LOCKBOX_SECRET_KEY=YOUR_LOCKBOX_SECRET_KEY'